In [1]:
import numpy as np

In [3]:
arr = np.array([(1, 2, 3, 4), (19, 5, 11, 7)])
print(arr[1])

[19  5 11  7]


In [4]:
print(arr[:, 0])

[ 1 19]


In [5]:
print(arr[0, 1:])

[2 3 4]


In [6]:
print(arr[::-1])

[[19  5 11  7]
 [ 1  2  3  4]]


In [8]:
arr1 = arr.reshape(1, 8)
arr1

array([[ 1,  2,  3,  4, 19,  5, 11,  7]])

In [14]:
arr.reshape(1, 8)

array([[ 1,  2,  3,  4, 19,  5, 11,  7]])

In [17]:
arr.ravel() # flatting the numpy array

array([ 1,  2,  3,  4, 19,  5, 11,  7])

In [18]:
arr

array([[ 1,  2,  3,  4],
       [19,  5, 11,  7]])

In [19]:
np.transpose(arr)

array([[ 1, 19],
       [ 2,  5],
       [ 3, 11],
       [ 4,  7]])

In [21]:
import cv2

In [22]:
image = np.zeros((500, 500))
image[:, :] = 100
image = image[:, :]+10
image[100:200, 200:300] = 255

cv2.imwrite('sample.jpg', image)

True