In [2]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [4]:
arr_v = np.array([[1], [2], [3]])
arr_v

array([[1],
       [2],
       [3]])

In [5]:
arr2 = np.array([[(1,2,3), (3, 4, 5)], [(1,2,3), (3, 4, 5)]])
arr2

array([[[1, 2, 3],
        [3, 4, 5]],

       [[1, 2, 3],
        [3, 4, 5]]])

In [6]:
arr_zero = np.zeros((3, 3), dtype="uint")
arr_zero

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint64)

In [7]:
arr_one = np.ones((3, 5), dtype="uint")
arr_one

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint64)

In [8]:
arr_full = np.full((3, 5), 5)
arr_full

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [9]:
arr_eye = np.eye(3)
arr_eye

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
arr_arange = np.arange(0, 10, 6)
arr_arange

array([0, 6])

In [11]:
arr_linspace = np.linspace(0, 2, 9)
arr_linspace

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [12]:
arr_random = np.random.rand(2, 3)*255
arr_random

array([[124.12349913, 115.20726144, 221.58499559],
       [ 59.52102103, 108.23449463,  87.66130362]])

In [13]:
arr_randomint = np.random.randint(5, size=(3,3))
arr_randomint

array([[2, 0, 4],
       [0, 2, 0],
       [1, 3, 2]])

In [16]:
arr2.shape

(2, 2, 3)